<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Add Customer Test"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="7.993">
  <properties />
            <testcase name="addCustomerTest" time="7.993" classname="com.w2a.testcases.AddCustomerTest">
                <failure type="java.lang.AssertionError"
                  message="Customer Not Added Successfully  !!!"
              >
<![CDATA[java.lang.AssertionError: Customer Not Added Successfully  !!!
  org.testng.Assert.fail(Assert.java:99)
  com.w2a.testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:30)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:483)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  org.testng.TestRunner$$Lambda$310/2116179210.accept(Unknown Source)
  java.util.ArrayList.forEach(ArrayList.java:1234)
  org.testng.TestRunner.privateRun(TestRunner.java:794)
  org.testng.TestRunner.run(TestRunner.java:596)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
  org.testng.SuiteRunner.run(SuiteRunner.java:276)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
  org.testng.TestNG.runSuites(TestNG.java:1063)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
