<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-O391UBK" name="com.w2a.testcases.AddCustomerTest" tests="1" failures="1" timestamp="2021-11-06T23:12:14 IST" time="7.993" errors="0">
  <testcase name="addCustomerTest" time="7.993" classname="com.w2a.testcases.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="Customer Not Added Successfully  !!!">
      <![CDATA[java.lang.AssertionError: Customer Not Added Successfully  !!!
at org.testng.Assert.fail(Assert.java:99)
at com.w2a.testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$310/2116179210.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1234)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addCustomerTest -->
  <system-out>
    <![CDATA[Capturing Screenshot
<a target ="_blank" href="E:\Wallpaper\bike_chase.jpg">Screenshot</a>
<br>
<a target ="_blank" href="E:\Wallpaper\bike_chase.jpg"><img src="E:\Wallpaper\bike_chase.jpg" height=200 width=300></img></a>]]>
  </system-out>
</testsuite> <!-- com.w2a.testcases.AddCustomerTest -->
